### ISSUE TITLE
offhand issues

### ISSUE THREAD

**Issue by PhanaticD** [Bimmr/McInfected#124]
eating gold apples with offhand causes the normal golden apple effects and isnt instant

if you are holding a weapon in your main hand it will also cause the weapon to be consumed and not the apple

**Comment by Bimmr** [comment]
I've fixed the weapon disappearing, but as for the not instant eating... I'll have to look into it because in theory it should work the same as in your main hand.

**Comment by Bimmr** [comment]
Fixed

**Comment by PhanaticD** [comment]
this is still happening with the version you uploaded yesterday

**Comment by Bimmr** [comment]
The version I uploaded to Spigot should solve that issue.
